# Generated by Django 4.0.6 on 2022-07-12 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='sp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sp_chat', to='service_provider.serviceprovider'),
        ),
    ]
