# Generated by Django 4.0.6 on 2022-07-11 13:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service_provider', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['user__username']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['texted_at']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['ordered_at']},
        ),
        migrations.AlterModelOptions(
            name='serviceprovider',
            options={'ordering': ['user__username']},
        ),
    ]
