# Generated by Django 4.0.6 on 2022-07-17 07:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service_provider', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='user2',
            new_name='sp',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='user1',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('sp', 'user')},
        ),
    ]
