# Generated by Django 4.0.6 on 2022-07-12 16:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0002_alter_chat_sp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='location',
            name='y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='range',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='range',
            name='radius',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='range',
            name='x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='range',
            name='y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='avr_rating',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sp', to='service_provider.category'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='rate_per_hour',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
