# Generated by Django 4.0.6 on 2022-07-13 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0003_alter_location_x_alter_location_y_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='range',
            name='id',
        ),
        migrations.AlterField(
            model_name='range',
            name='sp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='range', serialize=False, to='service_provider.serviceprovider'),
        ),
    ]
