# Generated by Django 4.0.6 on 2022-07-15 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0005_remove_review_id_alter_review_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='avr_rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
