# Generated by Django 4.0.6 on 2022-07-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
